version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  terragrunt-plan:
    docker:
      - image: alpine/terragrunt:1.5.3
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $AWS_ADMIN_OIDC_ROLE
      - run:
          name: View AWS Creds
          command: |
            cat ~/.aws/credentials
            cat ~/.aws/config
      - run:
          name: Terragrunt Plan
          command: |
            TF_TOKEN_app_terraform_io=$TERRAGRUNT_TFC_INTEGRATION_TOKEN terragrunt run-all plan

workflows:
  continuous-integration:
    jobs:
      - terragrunt-plan:
          context: [AWS, TFC]
