version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  terragrunt-validate:
    docker:
      - image: alpine/terragrunt:1.5.3
    steps:
      - checkout
      - run:
          name: Terragrunt Validate
          command: |
            TF_TOKEN_app_terraform_io=$TERRAGRUNT_TFC_INTEGRATION_TOKEN \
            terragrunt run-all validate

  terragrunt-plan:
    docker:
      - image: alpine/terragrunt:1.5.3
    steps:
      - checkout
      - run:
          name: Terragrunt Plan
          command: |
            TF_TOKEN_app_terraform_io=$TERRAGRUNT_TFC_INTEGRATION_TOKEN \
            terragrunt run-all plan

  terragrunt-apply:
    docker:
      - image: alpine/terragrunt:1.5.3
    steps:
      - checkout
      - run:
          name: Terragrunt Apply
          command: |
            TF_TOKEN_app_terraform_io=$TERRAGRUNT_TFC_INTEGRATION_TOKEN \
            terragrunt run-all apply

workflows:
  continuous-integration:
    jobs:
      - terragrunt-validate
      - terragrunt-plan:
          context: [TFC]
